# Project: Project1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = "Exercise\ 4/lesson4.o"
LINKOBJ  = "Exercise 4/lesson4.o"
LIBS     = -L"D:/Download/Dev-Cpp/MinGW64/lib" -L"D:/Download/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Download/Dev-Cpp/MinGW64/include" -I"D:/Download/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Download/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Download/Dev-Cpp/MinGW64/include" -I"D:/Download/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Download/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Download/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = lesson4.exe
CXXFLAGS = $(CXXINCS) -std=c99
CFLAGS   = $(INCS) -std=c99
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

"Exercise\ 4/lesson4.o": Exercise\ 4/lesson4.c
	$(CC) -c "Exercise 4/lesson4.c" -o "Exercise 4/lesson4.o" $(CFLAGS)
